version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fakeorgasm-db
    environment:
      POSTGRES_DB: FakeOrgasm
      POSTGRES_USER: fakeLibrary
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Montar el script SQL

volumes:
  pgdata:
