@startuml
package "req [Package] Book management [requirement diagram]" {
    stereotype "Repository interface" as repository_interface <<Requirement>> {
        overview = Interface to manage the books
    }

    stereotype "Book repository" as book_repository <<Requirement>> {
        overview = Allow the library staff to add, update, and remove books from the collection
        Book properties: title, author, ISBN, genre and publication year.
    }
    book_repository <.. repository_interface: <<deriveReqt>>

    stereotype "Navigation interface" as navigation_interface <<Requirement>> {
        overview = Interface to list books
    }

    stereotype "Book view" as list_view <<Requirement>> {
        overview = Books can be categorized by genres, and the system should support listing books by genre
    }
    list_view <.. navigation_interface: <<deriveReqt>>

    stereotype "Books management" as book_management <<Requirement>> {
        overview = The system should allow the library staff to add, update, and remove books from the collection. Each book
        should have properties like title, author, ISBN, genre, and publication year
        Books can be categorized by genres, and the system should support listing books by genre
    }
    book_management +-- list_view
    book_management +-- book_repository
}
@enduml

